title: Tanish Singh Kaler
logo: /assets/img/1623775198435.jfif
description: MS-Data Science Student at University of Arizona<br>Data Science Trainee at TuringMinds.Ai
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
